USERS_TABLE = "users"

USER_ID = "id"
USER_EMAIL = "email"
USER_PASSWORD_HASH = "password_hash"
USER_FIRST_NAME = "first_name"
USER_LAST_NAME = "last_name"
USER_DESCRIPTION = "description"
USER_ROLE_ID = "role_id"
USER_IS_VERIFIED = "is_verified"
USER_AVATAR_URL = "avatar_url"
USER_CREATED_AT = "created_at"

# Константы для таблицы подписок
SUBSCRIPTION_ID = "subscription_uuid"
SUBSCRIPTION_USER_ID = "user_id"
SUBSCRIPTION_COURSE_ID = "course_id"
SUBSCRIPTION_COURSE_NAME = "course_name"
SUBSCRIPTION_START_DATE = "start_date"
SUBSCRIPTION_END_DATE = "end_date"
SUBSCRIPTION_STATUS = "status"
SUBSCRIPTION_PRICE = "price"
SUBSCRIPTION_RECURRING = "recurring"
SUBSCRIPTION_CREATED_AT = "created_at"
SUBSCRIPTION_UPDATED_AT = "updated_at"

# Константы для таблицы платежей
PAYMENT_ID = "payment_id"
PAYMENT_USER_ID = "user_id"
PAYMENT_COURSE_ID = "course_id"
PAYMENT_COURSE_NAME = "course_name"
PAYMENT_DATE = "payment_date"
PAYMENT_AMOUNT = "amount"
PAYMENT_STATUS = "status"
PAYMENT_METHOD = "payment_method"
PAYMENT_CREATED_AT = "created_at"

# Константы для таблицы методов оплаты
PAYMENT_METHOD_ID = "payment_method_id"
PAYMENT_METHOD_USER_ID = "user_id"
PAYMENT_METHOD_TYPE = "method_type"
PAYMENT_METHOD_DETAILS = "details"
PAYMENT_METHOD_IS_DEFAULT = "is_default"
PAYMENT_METHOD_CREATED_AT = "created_at"
PAYMENT_METHOD_UPDATED_AT = "updated_at" 