USERS_TABLE = "users"
VERIFICATION_CODES_TABLE = "verification_codes"
RESET_CODES_TABLE = "reset_codes"
EMAIL_CHANGE_CODES_TABLE = "email_change_codes"
PASSWORD_VERSIONS_TABLE = "password_versions"
BLACKLISTED_TOKENS_TABLE = "blacklisted_tokens"

USER_ID = "id"
USER_EMAIL = "email"
USER_PASSWORD_HASH = "password_hash"
USER_FIRST_NAME = "first_name"
USER_LAST_NAME = "last_name"
USER_ROLE_ID = "role_id"
USER_IS_VERIFIED = "is_verified"
USER_AVATAR_URL = "avatar_url"
USER_CREATED_AT = "created_at"

VERIFICATION_CODE_ID = "id"
VERIFICATION_CODE_USER_ID = "user_id"
VERIFICATION_CODE = "verification_code"
VERIFICATION_CODE_CREATED_AT = "created_at"

RESET_CODE_ID = "id"
RESET_CODE_USER_ID = "user_id"
RESET_CODE = "reset_code"
RESET_CODE_CREATED_AT = "created_at"

EMAIL_CHANGE_CODE_ID = "id"
EMAIL_CHANGE_CODE_USER_ID = "user_id"
EMAIL_CHANGE_CODE_NEW_EMAIL = "new_email"
EMAIL_CHANGE_CODE = "code"
EMAIL_CHANGE_CODE_CREATED_AT = "created_at"

PASSWORD_VERSION_USER_ID = "user_id"
PASSWORD_VERSION_VERSION = "version"
PASSWORD_VERSION_CREATED_AT = "created_at"

BLACKLISTED_TOKEN_ID = "id"
BLACKLISTED_TOKEN_TOKEN = "token"
BLACKLISTED_TOKEN_EXPIRES_AT = "expires_at" 